/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario.original;

import Clases.Conexion;
 import Clases.ConexionBD;
import static Clases.ConexionBD.ConectarBD;
import static Clases.Metdos_sql.conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Actualizar_productossalonteatro extends javax.swing.JDialog {

    /**
     * Creates new form Actualizar_productossalonteatro
     */
    public Actualizar_productossalonteatro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nombret = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        referenciat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        descripciont = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tipot = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(0, 204, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ACTUALIZAR");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel3.setText("NOMBRE:");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        nombret.setBackground(new java.awt.Color(0, 204, 0));
        nombret.setBorder(null);
        nombret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombretActionPerformed(evt);
            }
        });
        panel1.add(nombret, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 280, 20));

        jLabel4.setText("REFERENCIA:");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        referenciat.setBackground(new java.awt.Color(0, 204, 0));
        referenciat.setBorder(null);
        panel1.add(referenciat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 270, 20));

        jLabel6.setText("DESCRIPCION:");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        descripciont.setBackground(new java.awt.Color(0, 204, 0));
        descripciont.setBorder(null);
        descripciont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripciontActionPerformed(evt);
            }
        });
        panel1.add(descripciont, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 260, 20));

        jLabel7.setText("TIPO:");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        tipot.setBackground(new java.awt.Color(0, 204, 0));
        tipot.setBorder(null);
        tipot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipotActionPerformed(evt);
            }
        });
        panel1.add(tipot, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 310, 20));

        btnactualizar.setBackground(new java.awt.Color(0, 204, 0));
        btnactualizar.setText("ACTUALIZAR");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        panel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 120, 40));

        btnSalir.setBackground(new java.awt.Color(0, 204, 0));
        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 100, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 340, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 340, 20));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 20));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        panel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 340, 20));

        jLabel2.setText("id:");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        panel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void descripciontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripciontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripciontActionPerformed

    private void tipotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipotActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        try {
           Conexion Con = new Conexion();
           Con.ConectarBD();
         String idt = id.getText();  
        String nombre = nombret.getText();
        String referencia = referenciat.getText();
        String descripcion = descripciont.getText();
        String tipo=tipot.getText();
        
           String SQL = "UPDATE producto_salonteatro SET "
                    + "id_producto_t='"+idt+"',nombre_ot='"+nombre+"',referencia_ot='"+referencia+"',descripcion_t='"+descripcion+"',tipo_t='"+tipo+"'"
                   +"WHERE  id_producto_t='"+idt+"'";
           Con.sentencia.execute(SQL);
           JOptionPane.showMessageDialog(null,
                   "¡Registro Actualizado con Exito!");
           dispose();
           Con.DesconectarBD();
       }catch (SQLException ex) {
        Logger.getLogger(Actualizar_productossalonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }

         setVisible(false);
        Inventario_salonteatro q =new Inventario_salonteatro();
         
       
        q.setVisible (true);
         q.pninventario.setVisible(false);
    q.pnproductos.setVisible(true);
     q.pnentradas.setVisible(false);
      q.pnsalidas.setVisible(false);
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       setVisible(false);
        Inventario_salonteatro q =new Inventario_salonteatro();
        q.setVisible (true);
         q.pninventario.setVisible(false);
    q.pnproductos.setVisible(true);
     q.pnentradas.setVisible(false);
      q.pnsalidas.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void referencia_otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referencia_otActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referencia_otActionPerformed

    private void nombretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombretActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombretActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Actualizar_productossalonteatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Actualizar_productossalonteatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Actualizar_productossalonteatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Actualizar_productossalonteatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Actualizar_productossalonteatro dialog = new Actualizar_productossalonteatro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnactualizar;
    public javax.swing.JTextField descripciont;
    public javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JTextField nombret;
    private java.awt.Panel panel1;
    public javax.swing.JTextField referenciat;
    public javax.swing.JTextField tipot;
    // End of variables declaration//GEN-END:variables
}
