/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario.original;

import Clases.Conexion;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SALA1-PC05
 */
public class Entrada_t extends javax.swing.JDialog {

    /**
     * Creates new form Entrada_t
     */
    public Entrada_t(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id_entrada_t = new javax.swing.JTextField();
        cantidad_entrada_t = new javax.swing.JTextField();
        descripcion_entrada_t = new javax.swing.JTextField();
        fecha_entrada_t = new javax.swing.JTextField();
        hora_entrada_t = new javax.swing.JTextField();
        btnGuardar_entrada_t = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("id:");

        jLabel3.setText("cantidad:");

        jLabel4.setText("descripcion");

        jLabel6.setText("fecha:");

        jLabel7.setText("hora:");

        hora_entrada_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora_entrada_tActionPerformed(evt);
            }
        });

        btnGuardar_entrada_t.setText("GUARDAR");
        btnGuardar_entrada_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_entrada_tActionPerformed(evt);
            }
        });

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cantidad_entrada_t))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(hora_entrada_t))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(descripcion_entrada_t))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(fecha_entrada_t)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(id_entrada_t, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuardar_entrada_t)
                    .addComponent(jButton1))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_entrada_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cantidad_entrada_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar_entrada_t))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(descripcion_entrada_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fecha_entrada_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(hora_entrada_t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardar_entrada_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_entrada_tActionPerformed
   Conexion Con = new Conexion();
        Con.ConectarBD();
        
        String id;
       
        
        String cantidad= cantidad_entrada_t.getText();
        String descripcion= descripcion_entrada_t.getText();
        String fecha = fecha_entrada_t.getText();
        String hora = hora_entrada_t.getText();
         
        
            if(!cantidad.isEmpty()){
                if(!descripcion.isEmpty()){
                    if(!fecha.isEmpty()){
                        if(!hora.isEmpty()){
                        try {
                      String SQL = "INSERT INTO entrada_t"
                              +"(cantidad_t,descripcion_t,fecha_t,hora_t)"
                              +"VALUE"
                              +"('"+cantidad+"','"+descripcion+"','"+fecha+"','"+hora+"');";
                      Con.sentencia.execute(SQL);
                      JOptionPane.showMessageDialog(null,"LOS DATOS FUERON GUARDADOS CON EXITO!");     
                      
                       } catch (SQLException ex) {
                          Logger.getLogger(Agregar_productossalonteatro.class.getName()).log(Level.SEVERE, null, ex);
                   }
                
                } else {JOptionPane.showMessageDialog(null,"");
                        
                        }
            
            } else{JOptionPane.showMessageDialog(null,"");
                    }
        
        }else{JOptionPane.showMessageDialog(null,"");
        
     }}
          Con.DesconectarBD();
        
                               
        
       setVisible(false);
        Inventario_salonteatro q =new Inventario_salonteatro();
        q.setVisible (true);
         q.pninventario.setVisible(false);
    q.pnproductos.setVisible(false);
     q.pnentradas.setVisible(true);
      q.pnsalidas.setVisible(false);
        
        
        
        
        
        
    }//GEN-LAST:event_btnGuardar_entrada_tActionPerformed

    private void hora_entrada_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora_entrada_tActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora_entrada_tActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar_entrada_t;
    private javax.swing.JTextField cantidad_entrada_t;
    private javax.swing.JTextField descripcion_entrada_t;
    private javax.swing.JTextField fecha_entrada_t;
    private javax.swing.JTextField hora_entrada_t;
    private javax.swing.JTextField id_entrada_t;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
