/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario.original;

import Clases.Conexion;
import Clases.ConexionBD;
import Clases.Metdos_sql;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Inventario_salonteatro extends javax.swing.JFrame {

    /**
     * Creates new form Inventario_salonteatro
     */
    public Inventario_salonteatro() {
        initComponents();
        setLocationRelativeTo(null);
        Crear_Modelo();
    }
 Metdos_sql metodos= new Metdos_sql();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        btnproductos = new javax.swing.JLabel();
        btnentradas = new javax.swing.JLabel();
        btnsalidas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btninventario = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        panel4 = new java.awt.Panel();
        pninventario = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnatrasi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnproductos = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTproductos_s = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        eliminarp = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        consultarp = new javax.swing.JButton();
        pnentradas = new java.awt.Panel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        consultaren = new javax.swing.JButton();
        atrasen = new javax.swing.JButton();
        pnsalidas = new java.awt.Panel();
        jLabel10 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton12 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setBackground(new java.awt.Color(0, 204, 0));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 204, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Inventario/drama-símbolo-comedia-teatro-máscaras-vectores-eps_csp68423939 (2).jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 170, 130));

        btnproductos.setBackground(new java.awt.Color(0, 204, 0));
        btnproductos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnproductos.setText("PRODUCTOS");
        btnproductos.setOpaque(true);
        btnproductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnproductosMouseClicked(evt);
            }
        });
        panel2.add(btnproductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 190, 40));

        btnentradas.setBackground(new java.awt.Color(0, 204, 0));
        btnentradas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnentradas.setText("ENTRADAS");
        btnentradas.setOpaque(true);
        btnentradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnentradasMouseClicked(evt);
            }
        });
        panel2.add(btnentradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 264, 190, 40));

        btnsalidas.setBackground(new java.awt.Color(0, 204, 0));
        btnsalidas.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnsalidas.setText("SALIDAS");
        btnsalidas.setOpaque(true);
        btnsalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsalidasMouseClicked(evt);
            }
        });
        panel2.add(btnsalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        panel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 190, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 190, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        panel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 190, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        panel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 10));

        btninventario.setBackground(new java.awt.Color(0, 204, 0));
        btninventario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btninventario.setText("INVENTARIO");
        btninventario.setOpaque(true);
        btninventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btninventarioMouseClicked(evt);
            }
        });
        panel2.add(btninventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 50));

        panel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 190, 510));

        panel3.setBackground(new java.awt.Color(0, 204, 0));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("INVENTARIO DEL SALON DE TEATRO");
        jLabel2.setOpaque(true);
        panel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, -1));

        panel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 40));

        panel4.setLayout(new java.awt.CardLayout());

        pninventario.setBackground(new java.awt.Color(0, 204, 0));
        pninventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setText("INVENTARIO");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pninventario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 190, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        pninventario.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 840, 370));

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("CONSULTAR");
        pninventario.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 140, 60));

        btnatrasi.setBackground(new java.awt.Color(0, 204, 0));
        btnatrasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnatrasi.setText("ATRAS");
        btnatrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasiActionPerformed(evt);
            }
        });
        pninventario.add(btnatrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 430, 130, 60));

        jButton2.setText("ENTRADA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pninventario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 433, -1, 60));

        panel4.add(pninventario, "card5");

        pnproductos.setBackground(new java.awt.Color(0, 204, 0));
        pnproductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTproductos_s.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTproductos_s);

        pnproductos.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 730, 430));

        jLabel8.setBackground(new java.awt.Color(51, 204, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("PRODUCTOS");
        pnproductos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 160, 60));

        agregar.setBackground(new java.awt.Color(0, 204, 0));
        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        pnproductos.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 110, 50));

        actualizar.setBackground(new java.awt.Color(0, 204, 0));
        actualizar.setText("ACTUALIZAR");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });
        pnproductos.add(actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 110, 50));

        eliminarp.setBackground(new java.awt.Color(0, 204, 0));
        eliminarp.setText("ELIMINAR");
        eliminarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarpActionPerformed(evt);
            }
        });
        pnproductos.add(eliminarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 110, 50));

        jButton10.setBackground(new java.awt.Color(0, 204, 0));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton10.setText("ATRAS");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        pnproductos.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 110, 50));

        consultarp.setBackground(new java.awt.Color(0, 204, 0));
        consultarp.setText("CONSULTAR");
        consultarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarpActionPerformed(evt);
            }
        });
        pnproductos.add(consultarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 110, 50));

        panel4.add(pnproductos, "card3");

        pnentradas.setBackground(new java.awt.Color(0, 204, 0));
        pnentradas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("ENTRADAS");
        pnentradas.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 140, 50));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        pnentradas.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 690, 440));

        consultaren.setBackground(new java.awt.Color(0, 204, 0));
        consultaren.setText("CONSULTAR");
        pnentradas.add(consultaren, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 150, 70));

        atrasen.setBackground(new java.awt.Color(0, 204, 0));
        atrasen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atrasen.setText("ATRAS");
        atrasen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasenActionPerformed(evt);
            }
        });
        pnentradas.add(atrasen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 60));

        panel4.add(pnentradas, "card4");

        pnsalidas.setBackground(new java.awt.Color(0, 204, 0));
        pnsalidas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("SALIDAS");
        pnsalidas.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 140, 50));

        jButton7.setBackground(new java.awt.Color(0, 204, 0));
        jButton7.setText("INGRESAR");
        pnsalidas.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 83, 150, 60));

        jButton8.setBackground(new java.awt.Color(0, 204, 0));
        jButton8.setText("CONSULTAR");
        pnsalidas.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 150, 70));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        pnsalidas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 690, 440));

        jButton12.setBackground(new java.awt.Color(0, 204, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton12.setText("ATRAS");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        pnsalidas.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 150, 60));

        panel4.add(pnsalidas, "card5");

        panel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 840, 500));

        jLabel3.setBackground(new java.awt.Color(0, 204, 0));
        jLabel3.setOpaque(true);
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 840, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninventarioMouseClicked
   pninventario.setVisible(true);
    pnproductos.setVisible(false);
     pnentradas.setVisible(false);
      pnsalidas.setVisible(false);
    }//GEN-LAST:event_btninventarioMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnproductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnproductosMouseClicked
        pninventario.setVisible(false);
    pnproductos.setVisible(true);
     pnentradas.setVisible(false);
      pnsalidas.setVisible(false);
    }//GEN-LAST:event_btnproductosMouseClicked

    private void btnentradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnentradasMouseClicked
        pninventario.setVisible(false);
    pnproductos.setVisible(false);
     pnentradas.setVisible(true);
      pnsalidas.setVisible(false);
    }//GEN-LAST:event_btnentradasMouseClicked

    private void btnsalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalidasMouseClicked
        pninventario.setVisible(false);
    pnproductos.setVisible(false);
     pnentradas.setVisible(false);
      pnsalidas.setVisible(true);
    }//GEN-LAST:event_btnsalidasMouseClicked

    private void btnatrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasiActionPerformed
        setVisible(false);
        Inventarios e=new Inventarios();
        e.setVisible(true);
    }//GEN-LAST:event_btnatrasiActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        setVisible(false);
        Inventarios mu=new Inventarios();
       mu.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void atrasenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasenActionPerformed
       setVisible(false);
        Inventarios ea=new Inventarios();
        ea.setVisible(true);
    }//GEN-LAST:event_atrasenActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
      setVisible(false);
        Inventarios eq=new Inventarios();
        eq.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        setVisible(false);
        Agregar_productossalonteatro wq= new Agregar_productossalonteatro(null,true);
        wq.setVisible(true);
    }//GEN-LAST:event_agregarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
    String id = jTproductos_s.getValueAt(jTproductos_s.getSelectedRow(),0).toString();   
    String nombre = jTproductos_s.getValueAt(jTproductos_s.getSelectedRow(), 1).toString();
    String referencia = jTproductos_s.getValueAt(jTproductos_s.getSelectedRow(), 2).toString();
    String descripcion = jTproductos_s.getValueAt(jTproductos_s.getSelectedRow(), 3).toString();
    String tipo = jTproductos_s.getValueAt(jTproductos_s.getSelectedRow(), 4).toString(); 
        setVisible(false);
        Actualizar_productossalonteatro wwq= new Actualizar_productossalonteatro(null,true);
        wwq.id.setText(id);
        wwq.nombret.setText(nombre);
        wwq.referenciat.setText(referencia);
        wwq.descripciont.setText(descripcion);
        wwq.tipot.setText(tipo);
        wwq.setVisible(true);
    }//GEN-LAST:event_actualizarActionPerformed

    private void consultarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarpActionPerformed
      Consultarp();
   
    }//GEN-LAST:event_consultarpActionPerformed

    private void eliminarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarpActionPerformed
           try {
            String id = jTproductos_s.getValueAt(jTproductos_s.getSelectedRow(), 0).toString();
            Conexion Con = new Conexion();
            Con.ConectarBD();
            String SQL = "DELETE FROM producto_salonteatro WHERE id_producto_t='"+id+"'";
            Con.sentencia.execute(SQL);
            JOptionPane.showMessageDialog(null, "¡El registro fue eliminado!");
            Con.DesconectarBD();
        } catch (SQLException ex) {
            Logger.getLogger(Inventario_salonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }
              Crear_Modelo();
              Consultarp();
    }//GEN-LAST:event_eliminarpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        Entrada_t c = new Entrada_t(null,true);
c.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

       DefaultTableModel modelo;
    private void Crear_Modelo(){
    try{
        modelo=(new DefaultTableModel(
                null, new String[]{
                    
                    "id","Nombre","Referencia","Descripcion",
                    "Tipo"}) {
                        
                    Class[] types = new Class[]{
                        
                        java.lang.String.class,java.lang.String.class,
                        java.lang.String.class,java.lang.String.class,java.lang.String.class
                      
                        };
                        boolean[] canEdit = new boolean[]{
                            false,false,false,false,false
                        };
                        public Class getColumnClass(int columnIndex){
                        return types[columnIndex];
                        }
                        public boolean isCellEditable(int rowIndex, int colIndex){
                        return canEdit[colIndex];
                        }
          
                     });
                    jTproductos_s.setModel(modelo);
                    } catch (Exception e){
                            JOptionPane.showMessageDialog(null,e.toString()+"Error");
                    }
    }
       private void Consultarp(){
        try {
            int i = 0; Object Ob[]=null;
            Conexion con = new Conexion();
            con.ConectarBD();
            String SQL = "SELECT * FROM producto_salonteatro";
            con.resultado = con.sentencia.executeQuery(SQL);
            while (con.resultado.next()){
                modelo.addRow(Ob);
                modelo.setValueAt(con.resultado.getString("id_producto_t"),i,0);
                modelo.setValueAt(con.resultado.getString("nombre_ot"), i, 1);
                modelo.setValueAt(con.resultado.getString("referencia_ot"), i, 2);
                modelo.setValueAt(con.resultado.getString("descripcion_t"), i, 3);
                modelo.setValueAt(con.resultado.getString("tipo_t"), i, 4);
              
                i++;
            }
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Inventario_salonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JButton atrasen;
    private javax.swing.JButton btnatrasi;
    public javax.swing.JLabel btnentradas;
    public javax.swing.JLabel btninventario;
    public javax.swing.JLabel btnproductos;
    public javax.swing.JLabel btnsalidas;
    private javax.swing.JButton consultaren;
    private javax.swing.JButton consultarp;
    private javax.swing.JButton eliminarp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTproductos_s;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    public java.awt.Panel pnentradas;
    public java.awt.Panel pninventario;
    public java.awt.Panel pnproductos;
    public java.awt.Panel pnsalidas;
    // End of variables declaration//GEN-END:variables
}
