/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario.original;

import Clases.Metdos_sql;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Registrarse extends javax.swing.JDialog {

    /**
     * Creates new form Registrarse
     */
    public Registrarse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
      Metdos_sql metodos= new Metdos_sql();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnd = new javax.swing.JTextField();
        txtnc = new javax.swing.JTextField();
        txtc = new javax.swing.JTextField();
        txtco = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        guardarl = new javax.swing.JButton();
        atrasl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("REGISTRARSE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 260, -1));

        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("NOMBRE COMPLETO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("NUMERO DE DOCUMENTO:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("CORREO:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("CONTRASEÑA:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txtnd.setBackground(new java.awt.Color(0, 0, 0));
        txtnd.setForeground(new java.awt.Color(255, 255, 255));
        txtnd.setBorder(null);
        txtnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtndActionPerformed(evt);
            }
        });
        jPanel1.add(txtnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 180, 20));

        txtnc.setBackground(new java.awt.Color(0, 0, 0));
        txtnc.setForeground(new java.awt.Color(255, 255, 255));
        txtnc.setBorder(null);
        jPanel1.add(txtnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 210, 20));

        txtc.setBackground(new java.awt.Color(0, 0, 0));
        txtc.setForeground(new java.awt.Color(255, 255, 255));
        txtc.setBorder(null);
        jPanel1.add(txtc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 280, 20));

        txtco.setBackground(new java.awt.Color(0, 0, 0));
        txtco.setForeground(new java.awt.Color(255, 255, 255));
        txtco.setBorder(null);
        jPanel1.add(txtco, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 340, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 340, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 340, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 340, 10));

        guardarl.setBackground(new java.awt.Color(0, 204, 0));
        guardarl.setText("GUARDAR");
        guardarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarlActionPerformed(evt);
            }
        });
        jPanel1.add(guardarl, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, -1));

        atrasl.setBackground(new java.awt.Color(0, 204, 0));
        atrasl.setText("ATRAS");
        atrasl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atraslActionPerformed(evt);
            }
        });
        jPanel1.add(atrasl, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarlActionPerformed
       int i= metodos.guardar(txtnd.getText(), txtnc.getText(), txtc.getText(), txtco.getText());
       if(i>0){
           JOptionPane.showMessageDialog(this, "Su cuenta fue Creada");
       }else{
           JOptionPane.showMessageDialog(this, "No se pudo crear su cuenta, intente nuevamente");
       }
        setVisible(false);
        Iniciar ip= new Iniciar();
          ip.setVisible(true);
    }//GEN-LAST:event_guardarlActionPerformed

    private void atraslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atraslActionPerformed
         setVisible(false);
        Iniciar l= new Iniciar();
          l.setVisible(true);
    }//GEN-LAST:event_atraslActionPerformed

    private void txtndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registrarse dialog = new Registrarse(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasl;
    private javax.swing.JButton guardarl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtc;
    private javax.swing.JPasswordField txtco;
    private javax.swing.JTextField txtnc;
    private javax.swing.JTextField txtnd;
    // End of variables declaration//GEN-END:variables
}
