/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventario.nuevo;

import Clases.Conexion;
import Inventario.original.Inventario_salonteatro;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acampoes
 */
public class Inventarios extends javax.swing.JFrame {
    JTabbedPane tabs = new JTabbedPane();
    DefaultTableModel modeloTeatro;
    DefaultTableModel modeloQuimica;
    DefaultTableModel modeloInformatica;
    DefaultTableModel modeloDeporte;
    
    String[] titulos = {"ID", "Nombre","Referencia","Descripción","Tipo"};
    /**
     * Creates new form Inventarios
     */
    public Inventarios() {
        initComponents();
        this.tabs = pnlTabs;
        this.modeloDeporte = new DefaultTableModel(null, titulos);
        this.modeloInformatica = new DefaultTableModel(null, titulos);
        this.modeloQuimica = new DefaultTableModel(null, titulos);
        this.modeloTeatro = new DefaultTableModel(null, titulos);
        tblDeporte.setModel(modeloDeporte);
        tblInformatica.setModel(modeloInformatica);
        tblQuimica.setModel(modeloQuimica);
        tblTeatro.setModel(modeloTeatro);
        this.setLocationRelativeTo(null);
    }
    
    
       private void ConsultaSalonQuimica(){
        try {
            int i = 0; Object Ob[]=null;
            Conexion con = new Conexion();
            con.ConectarBD();
            String SQL = "SELECT * FROM producto_salonteatro";
            con.resultado = con.sentencia.executeQuery(SQL);
            while (con.resultado.next()){
                modeloQuimica.addRow(Ob);
                modeloQuimica.setValueAt(con.resultado.getString("id_producto_t"),i,0);
                modeloQuimica.setValueAt(con.resultado.getString("nombre_ot"), i, 1);
                modeloQuimica.setValueAt(con.resultado.getString("referencia_ot"), i, 2);
                modeloQuimica.setValueAt(con.resultado.getString("descripcion_t"), i, 3);
                modeloQuimica.setValueAt(con.resultado.getString("tipo_t"), i, 4);
              
                i++;
            }
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Inventario_salonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       private void ConsultaSalonDeporte(){
        try {
            int i = 0; Object Ob[]=null;
            Conexion con = new Conexion();
            con.ConectarBD();
            String SQL = "SELECT * FROM producto_salonteatro";
            con.resultado = con.sentencia.executeQuery(SQL);
            while (con.resultado.next()){
                modeloDeporte.addRow(Ob);
                modeloDeporte.setValueAt(con.resultado.getString("id_producto_t"),i,0);
                modeloDeporte.setValueAt(con.resultado.getString("nombre_ot"), i, 1);
                modeloDeporte.setValueAt(con.resultado.getString("referencia_ot"), i, 2);
                modeloDeporte.setValueAt(con.resultado.getString("descripcion_t"), i, 3);
                modeloDeporte.setValueAt(con.resultado.getString("tipo_t"), i, 4);
              
                i++;
            }
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Inventario_salonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       private void ConsultaSalonInformatica(){
        try {
            int i = 0; Object Ob[]=null;
            Conexion con = new Conexion();
            con.ConectarBD();
            String SQL = "SELECT * FROM producto_salonteatro";
            con.resultado = con.sentencia.executeQuery(SQL);
            while (con.resultado.next()){
                modeloInformatica.addRow(Ob);
                modeloInformatica.setValueAt(con.resultado.getString("id_producto_t"),i,0);
                modeloInformatica.setValueAt(con.resultado.getString("nombre_ot"), i, 1);
                modeloInformatica.setValueAt(con.resultado.getString("referencia_ot"), i, 2);
                modeloInformatica.setValueAt(con.resultado.getString("descripcion_t"), i, 3);
                modeloInformatica.setValueAt(con.resultado.getString("tipo_t"), i, 4);
              
                i++;
            }
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Inventario_salonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlTabs = new javax.swing.JTabbedPane();
        panelTeatro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeatro = new javax.swing.JTable();
        cmdIngresarTeatro = new javax.swing.JButton();
        cmdUpdateTeatro = new javax.swing.JButton();
        cmdRefreshTeatro = new javax.swing.JButton();
        panelQuimica = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblQuimica = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        panelInformatica = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInformatica = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDeporte = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inventarios IDETP");

        tblTeatro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTeatro);

        cmdIngresarTeatro.setText("Ingresar");

        cmdUpdateTeatro.setText("Modificar");

        cmdRefreshTeatro.setText("Actualizar");
        cmdRefreshTeatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRefreshTeatroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTeatroLayout = new javax.swing.GroupLayout(panelTeatro);
        panelTeatro.setLayout(panelTeatroLayout);
        panelTeatroLayout.setHorizontalGroup(
            panelTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeatroLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(panelTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelTeatroLayout.createSequentialGroup()
                        .addComponent(cmdRefreshTeatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdIngresarTeatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdUpdateTeatro))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        panelTeatroLayout.setVerticalGroup(
            panelTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeatroLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTeatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdIngresarTeatro)
                    .addComponent(cmdUpdateTeatro)
                    .addComponent(cmdRefreshTeatro))
                .addContainerGap())
        );

        pnlTabs.addTab("Salón de Teatro", panelTeatro);

        tblQuimica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblQuimica);

        jButton7.setText("Modificar");

        jButton8.setText("Ingresar");

        jButton9.setText("Actualizar");

        javax.swing.GroupLayout panelQuimicaLayout = new javax.swing.GroupLayout(panelQuimica);
        panelQuimica.setLayout(panelQuimicaLayout);
        panelQuimicaLayout.setHorizontalGroup(
            panelQuimicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelQuimicaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelQuimicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQuimicaLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(215, 215, 215)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelQuimicaLayout.setVerticalGroup(
            panelQuimicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQuimicaLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQuimicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Salón de Química", panelQuimica);

        tblInformatica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblInformatica);

        jButton4.setText("Modificar");

        jButton5.setText("Ingresar");

        jButton6.setText("Actualizar");

        javax.swing.GroupLayout panelInformaticaLayout = new javax.swing.GroupLayout(panelInformatica);
        panelInformatica.setLayout(panelInformaticaLayout);
        panelInformaticaLayout.setHorizontalGroup(
            panelInformaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInformaticaLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(panelInformaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformaticaLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(215, 215, 215)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelInformaticaLayout.setVerticalGroup(
            panelInformaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformaticaLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformaticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Sala de Informática", panelInformatica);

        tblDeporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblDeporte);

        jButton1.setText("Actualizar");

        jButton2.setText("Modificar");

        jButton3.setText("Ingresar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(215, 215, 215)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlTabs.addTab("Salón de Deporte", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabs)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRefreshTeatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRefreshTeatroActionPerformed
        try {
            int i = 0; Object Ob[]=null;
            Conexion con = new Conexion();
            con.ConectarBD();
            String SQL = "SELECT * FROM producto_salonteatro";
            con.resultado = con.sentencia.executeQuery(SQL);
            while (con.resultado.next()){
                modeloTeatro.addRow(Ob);
                modeloTeatro.setValueAt(con.resultado.getString("id_producto_t"),i,0);
                modeloTeatro.setValueAt(con.resultado.getString("nombre_ot"), i, 1);
                modeloTeatro.setValueAt(con.resultado.getString("referencia_ot"), i, 2);
                modeloTeatro.setValueAt(con.resultado.getString("descripcion_t"), i, 3);
                modeloTeatro.setValueAt(con.resultado.getString("tipo_t"), i, 4);
              
                i++;
            }
            con.DesconectarBD();
        } catch (SQLException ex){
            Logger.getLogger(Inventario_salonteatro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdRefreshTeatroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdIngresarTeatro;
    private javax.swing.JButton cmdRefreshTeatro;
    private javax.swing.JButton cmdUpdateTeatro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panelInformatica;
    private javax.swing.JPanel panelQuimica;
    private javax.swing.JPanel panelTeatro;
    private javax.swing.JTabbedPane pnlTabs;
    private javax.swing.JTable tblDeporte;
    private javax.swing.JTable tblInformatica;
    private javax.swing.JTable tblQuimica;
    private javax.swing.JTable tblTeatro;
    // End of variables declaration//GEN-END:variables
}
